Run: 25
/cm/local/apps/slurm/var/spool/job969392/slurm_script: line 26: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 6 days ago.
starting loops
../data/r/197/197.pkl
working on 
../data/r/197/reg_full_MCAR_0.01_2
3.58609676361084
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-09-24 06:34:04,001] A new study created in memory with name: no-name-0781eaa0-44d9-4511-a531-7795c8cda741
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-09-24 06:34:04,232] Trial 13 finished with value: 0.178024056996342 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 13 with value: 0.178024056996342.
running
[I 2024-09-24 06:34:08,801] Trial 9 finished with value: 0.09964454268947594 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 5723, 'weights': 'uniform'}. Best is trial 9 with value: 0.09964454268947594.
running
[I 2024-09-24 06:34:09,135] Trial 6 finished with value: 0.08408390922075595 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1865, 'weights': 'uniform'}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:09,979] Trial 0 finished with value: 0.4449653156759723 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 1, 'learning_rate': 0.0052387752951411, 'p_miss': 0.19496496271779312}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:10,599] Trial 17 finished with value: 0.17675017307085134 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:10,845] Trial 19 finished with value: 0.10754797919449854 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:12,986] Trial 15 finished with value: 0.1959439207244639 and parameters: {'model_name': 'GAIN', 'batch_size': 8, 'hint_rate': 0.25804191983316094, 'alpha': 95, 'iterations': 1, 'learning_rate': 0.0004045626610464805, 'p_miss': 0.1372477567264012}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:18,758] Trial 12 finished with value: 0.19117393662929305 and parameters: {'model_name': 'GAIN', 'batch_size': 644, 'hint_rate': 0.6660705482378267, 'alpha': 13, 'iterations': 4, 'learning_rate': 0.0006230351386533008, 'p_miss': 0.08812085538102359}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:21,628] Trial 20 finished with value: 0.0978597345185369 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4642, 'weights': 'uniform'}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:22,878] Trial 22 finished with value: 0.08464651073828047 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1964, 'weights': 'uniform'}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:32,283] Trial 23 finished with value: 0.08962339214825046 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 4665, 'weights': 'distance'}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:48,673] Trial 4 finished with value: 0.11462764092473166 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 36, 'learning_rate': 0.008849965065559927, 'p_miss': 0.05727360091953351}. Best is trial 6 with value: 0.08408390922075595.
running
[I 2024-09-24 06:34:57,385] Trial 25 finished with value: 0.08060992760294987 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 2, 'imputation_order': 'ascending'}. Best is trial 25 with value: 0.08060992760294987.
running
[I 2024-09-24 06:35:00,960] Trial 21 finished with value: 0.444595072741372 and parameters: {'model_name': 'VAE', 'batch_size': 87, 'iterations': 37, 'learning_rate': 0.0001598300904535792, 'p_miss': 0.15362418364096744}. Best is trial 25 with value: 0.08060992760294987.
running
[I 2024-09-24 06:35:15,490] Trial 1 finished with value: 0.10475515613402901 and parameters: {'model_name': 'VAE', 'batch_size': 327, 'iterations': 12, 'learning_rate': 0.028813627621763104, 'p_miss': 0.22170275164793446}. Best is trial 25 with value: 0.08060992760294987.
running
[I 2024-09-24 06:35:17,278] Trial 7 finished with value: 0.10212818020494915 and parameters: {'model_name': 'VAE', 'batch_size': 15, 'iterations': 72, 'learning_rate': 0.01765515720049614, 'p_miss': 0.010002888282309153}. Best is trial 25 with value: 0.08060992760294987.
running
[I 2024-09-24 06:35:23,029] Trial 29 finished with value: 0.08945415923239106 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 1, 'imputation_order': 'ascending'}. Best is trial 25 with value: 0.08060992760294987.
running
[I 2024-09-24 06:35:40,351] Trial 30 finished with value: 0.08945415923239106 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 1, 'imputation_order': 'ascending'}. Best is trial 25 with value: 0.08060992760294987.
running
[I 2024-09-24 06:35:41,912] Trial 31 finished with value: 0.08945415923239106 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 1, 'imputation_order': 'ascending'}. Best is trial 25 with value: 0.08060992760294987.
running
[I 2024-09-24 06:35:42,586] Trial 28 finished with value: 0.0763146707951741 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 3, 'imputation_order': 'ascending'}. Best is trial 28 with value: 0.0763146707951741.
running
[I 2024-09-24 06:36:00,140] Trial 26 finished with value: 0.07737479384149844 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 3, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 28 with value: 0.0763146707951741.
running
[I 2024-09-24 06:36:14,303] Trial 24 finished with value: 0.0626371744605772 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 11, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 24 with value: 0.0626371744605772.
running
[I 2024-09-24 06:36:17,444] Trial 27 finished with value: 0.0535721894943574 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'median', 'n_nearest_features': 10, 'imputation_order': 'arabic'}. Best is trial 27 with value: 0.0535721894943574.
running
[I 2024-09-24 06:36:18,384] Trial 32 finished with value: 0.06760885425013233 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'most_frequent', 'n_nearest_features': 6, 'imputation_order': 'random'}. Best is trial 27 with value: 0.0535721894943574.
running
[I 2024-09-24 06:36:58,588] Trial 35 finished with value: 0.05486536401915134 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 12, 'imputation_order': 'random'}. Best is trial 27 with value: 0.0535721894943574.
running
[I 2024-09-24 06:37:06,447] Trial 3 finished with value: 0.11550258509386932 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 116, 'learning_rate': 0.0975127396117347, 'p_miss': 0.04482174175958407}. Best is trial 27 with value: 0.0535721894943574.
running
[I 2024-09-24 06:37:29,912] Trial 36 finished with value: 0.06490583890494572 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 27 with value: 0.0535721894943574.
running
[I 2024-09-24 06:37:35,377] Trial 39 finished with value: 0.051216485330443116 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 11, 'imputation_order': 'random'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:37:41,936] Trial 38 finished with value: 0.05157914686663323 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 13, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:38:05,535] Trial 37 finished with value: 0.060533527213978824 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 14, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:38:17,336] Trial 40 finished with value: 0.05359355366636305 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 13, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:38:29,588] Trial 41 finished with value: 0.0527373466256605 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 14, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:38:32,424] Trial 33 finished with value: 0.052662773972334 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'roman'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:38:34,098] Trial 34 finished with value: 0.05331767350307185 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 17, 'imputation_order': 'random'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:38:47,007] Trial 42 finished with value: 0.0527373466256605 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 14, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:39:49,793] Trial 43 finished with value: 0.052028838769022735 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 17, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:39:57,317] Trial 5 finished with value: 0.10546801866580668 and parameters: {'model_name': 'VAE', 'batch_size': 6, 'iterations': 149, 'learning_rate': 0.0023790354372704176, 'p_miss': 0.193276152853302}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:40:20,660] Trial 46 finished with value: 0.05321800407418855 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:40:33,909] Trial 47 finished with value: 0.05177389268275595 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 18, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 06:49:56,721] Trial 18 finished with value: 0.1631913687134204 and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.8192083866727178, 'alpha': 48, 'iterations': 680, 'learning_rate': 0.06986315044696295, 'p_miss': 0.2897428188547601}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 07:21:11,388] Trial 10 finished with value: 0.07803309001846444 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 2, 'imputation_order': 'descending'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 07:23:32,608] Trial 56 finished with value: 0.052662773972334 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'roman'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 07:58:34,575] Trial 16 finished with value: 0.1090111879780539 and parameters: {'model_name': 'VAE', 'batch_size': 3, 'iterations': 1748, 'learning_rate': 0.003881405183503449, 'p_miss': 0.15628842511761726}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:04:18,182] Trial 2 finished with value: 0.23708807769469337 and parameters: {'model_name': 'GAIN', 'batch_size': 609, 'hint_rate': 0.9491691330374973, 'alpha': 39, 'iterations': 2317, 'learning_rate': 0.006909929720715851, 'p_miss': 0.17619550552955393}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:06:15,225] Trial 59 finished with value: 0.051656924688563775 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 17, 'imputation_order': 'roman'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:15:10,360] Trial 55 finished with value: 0.10120289406567858 and parameters: {'model_name': 'VAE', 'batch_size': 63, 'iterations': 1978, 'learning_rate': 0.0024328248539626776, 'p_miss': 0.2768233498118075}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:28:31,576] Trial 44 finished with value: 0.31533581806665395 and parameters: {'model_name': 'GAIN', 'batch_size': 82, 'hint_rate': 0.9528657897394357, 'alpha': 69, 'iterations': 4327, 'learning_rate': 0.001671217062338415, 'p_miss': 0.29533132278129776}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:28:32,236] Trial 62 finished with value: 0.09964454268947594 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:30:27,421] Trial 63 finished with value: 0.05212490864345026 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 16, 'imputation_order': 'roman'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:32:25,425] Trial 64 finished with value: 0.052028838769022735 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 17, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:32:25,874] Trial 65 finished with value: 0.09964454268947594 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:34:22,884] Trial 66 finished with value: 0.052028838769022735 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 17, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:34:42,721] Trial 14 finished with value: 0.10028707432615244 and parameters: {'model_name': 'VAE', 'batch_size': 686, 'iterations': 1894, 'learning_rate': 0.00032101249034144623, 'p_miss': 0.12347254139497349}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:36:09,098] Trial 67 finished with value: 0.05177389268275595 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 18, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:36:27,387] Trial 68 finished with value: 0.0519780273689993 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 08:44:02,336] Trial 69 finished with value: 0.27779460466374706 and parameters: {'model_name': 'GAIN', 'batch_size': 30, 'hint_rate': 0.02667045766417825, 'alpha': 4, 'iterations': 357, 'learning_rate': 0.0009402546243333945, 'p_miss': 0.23095145611260118}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 09:02:10,880] Trial 53 finished with value: 0.3052894269666156 and parameters: {'model_name': 'GAIN', 'batch_size': 80, 'hint_rate': 0.9623432632808244, 'alpha': 72, 'iterations': 5833, 'learning_rate': 0.001255238837747813, 'p_miss': 0.2956544384638795}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 09:02:15,119] Trial 72 finished with value: 0.056715454948192176 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 36, 'weights': 'distance'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 09:24:18,696] Trial 51 finished with value: 0.30999466186485203 and parameters: {'model_name': 'GAIN', 'batch_size': 111, 'hint_rate': 0.9394431564301398, 'alpha': 70, 'iterations': 6605, 'learning_rate': 0.0023255573470687685, 'p_miss': 0.29634473734220745}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 09:37:49,010] Trial 54 finished with value: 0.3002109444584856 and parameters: {'model_name': 'GAIN', 'batch_size': 100, 'hint_rate': 0.9785763338009335, 'alpha': 74, 'iterations': 7191, 'learning_rate': 0.0008319116494821282, 'p_miss': 0.296122590218855}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 09:42:51,298] Trial 50 finished with value: 0.3012954787702401 and parameters: {'model_name': 'GAIN', 'batch_size': 75, 'hint_rate': 0.9083007622792982, 'alpha': 71, 'iterations': 7785, 'learning_rate': 0.0018382838054225767, 'p_miss': 0.2637957861945075}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 09:44:58,781] Trial 76 finished with value: 0.0519780273689993 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 09:47:09,854] Trial 77 finished with value: 0.0519780273689993 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 09:50:40,199] Trial 48 finished with value: 0.30342080757417256 and parameters: {'model_name': 'GAIN', 'batch_size': 75, 'hint_rate': 0.9768172893947555, 'alpha': 71, 'iterations': 8408, 'learning_rate': 0.0014726829202756078, 'p_miss': 0.2828808573835305}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 09:55:03,229] Trial 49 finished with value: 0.31138370361684625 and parameters: {'model_name': 'GAIN', 'batch_size': 75, 'hint_rate': 0.9159024709497494, 'alpha': 72, 'iterations': 8433, 'learning_rate': 0.0014930082629138362, 'p_miss': 0.2953575971434178}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 10:02:47,605] Trial 45 finished with value: 0.31404715643853215 and parameters: {'model_name': 'GAIN', 'batch_size': 87, 'hint_rate': 0.9898739139369623, 'alpha': 71, 'iterations': 8740, 'learning_rate': 0.0017991522361881548, 'p_miss': 0.29407605354406774}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 10:10:31,412] Trial 52 finished with value: 0.29490737389171534 and parameters: {'model_name': 'GAIN', 'batch_size': 80, 'hint_rate': 0.9816531545930403, 'alpha': 73, 'iterations': 9409, 'learning_rate': 0.001529548025020824, 'p_miss': 0.28850125776858}. Best is trial 39 with value: 0.051216485330443116.
running
[I 2024-09-24 10:36:25,039] Trial 70 finished with value: 0.039658407530270126 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 70 with value: 0.039658407530270126.
running
[I 2024-09-24 10:41:45,740] Trial 8 finished with value: 0.12098493463213333 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 6393, 'learning_rate': 0.06152056571801423, 'p_miss': 0.19357942075883264}. Best is trial 70 with value: 0.039658407530270126.
running
[I 2024-09-24 10:44:13,531] Trial 71 finished with value: 0.03949394053020468 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 71 with value: 0.03949394053020468.
running
[I 2024-09-24 10:46:35,880] Trial 11 finished with value: 0.10039844517075451 and parameters: {'model_name': 'VAE', 'batch_size': 80, 'iterations': 6669, 'learning_rate': 0.010523508438084802, 'p_miss': 0.25225055595926044}. Best is trial 71 with value: 0.03949394053020468.
running
[I 2024-09-24 10:49:35,308] Trial 61 finished with value: 0.28475086283847856 and parameters: {'model_name': 'GAIN', 'batch_size': 66, 'hint_rate': 0.01406005860854359, 'alpha': 97, 'iterations': 8049, 'learning_rate': 0.00010251191195702268, 'p_miss': 0.24564994860042189}. Best is trial 71 with value: 0.03949394053020468.
running
[I 2024-09-24 10:50:37,278] Trial 60 finished with value: 0.32319253389036773 and parameters: {'model_name': 'GAIN', 'batch_size': 63, 'hint_rate': 0.02577968784267598, 'alpha': 98, 'iterations': 8715, 'learning_rate': 0.0015567259496908038, 'p_miss': 0.28557104502282904}. Best is trial 71 with value: 0.03949394053020468.
running
[I 2024-09-24 10:51:23,514] Trial 58 finished with value: 0.31334559818700675 and parameters: {'model_name': 'GAIN', 'batch_size': 56, 'hint_rate': 0.04778964622732218, 'alpha': 97, 'iterations': 9561, 'learning_rate': 0.0010463015272874775, 'p_miss': 0.2897540071076841}. Best is trial 71 with value: 0.03949394053020468.
running
[I 2024-09-24 10:53:16,607] Trial 57 finished with value: 0.10082130133722819 and parameters: {'model_name': 'VAE', 'batch_size': 64, 'iterations': 8958, 'learning_rate': 0.0015906695696873985, 'p_miss': 0.2950497944121992}. Best is trial 71 with value: 0.03949394053020468.
running
[I 2024-09-24 10:59:48,370] Trial 73 finished with value: 0.0395557766209505 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 71 with value: 0.03949394053020468.
running
[I 2024-09-24 11:18:38,860] Trial 74 finished with value: 0.039550092823273604 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 71 with value: 0.03949394053020468.
running
[I 2024-09-24 11:28:16,389] Trial 75 finished with value: 0.03929982637745939 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 75 with value: 0.03929982637745939.
running
[I 2024-09-24 11:38:03,763] Trial 78 finished with value: 0.039221137283727864 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 78 with value: 0.039221137283727864.
running
[I 2024-09-24 11:38:41,258] Trial 79 finished with value: 0.039700207932786245 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 78 with value: 0.039221137283727864.
running
[I 2024-09-24 11:46:16,532] Trial 80 finished with value: 0.039066720511836725 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 11:50:44,159] Trial 81 finished with value: 0.03961730770380645 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 11:55:17,296] Trial 82 finished with value: 0.039247305232061165 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:15:53,330] Trial 83 finished with value: 0.0398177833752592 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:20:25,262] Trial 84 finished with value: 0.03938412322717542 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:24:51,619] Trial 86 finished with value: 0.03960896590529015 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:26:44,616] Trial 85 finished with value: 0.03917427272041519 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:26:46,529] Trial 102 finished with value: 0.0628487535135829 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 161, 'weights': 'distance'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:26:49,158] Trial 87 finished with value: 0.039308717450185514 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:27:38,882] Trial 88 finished with value: 0.03935339995672906 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:28:39,867] Trial 89 finished with value: 0.039356089218802556 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:30:07,620] Trial 90 finished with value: 0.0391371754599549 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:40:56,804] Trial 91 finished with value: 0.03918842375850316 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 12:59:44,824] Trial 92 finished with value: 0.039690504481857944 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 13:09:43,316] Trial 93 finished with value: 0.03923051830495837 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 13:19:11,305] Trial 94 finished with value: 0.03933078560808225 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 13:19:11,692] Trial 111 finished with value: 0.178024056996342 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 13:20:07,181] Trial 95 finished with value: 0.0394235560221884 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 13:27:24,618] Trial 96 finished with value: 0.0395609684213943 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 13:30:40,973] Trial 97 finished with value: 0.039106501884801644 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 13:36:20,559] Trial 98 finished with value: 0.03937344407651331 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 13:56:43,406] Trial 99 finished with value: 0.03916046844302461 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:00:37,332] Trial 100 finished with value: 0.039281839693017365 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:04:39,121] Trial 101 finished with value: 0.039197769486245926 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:06:37,477] Trial 104 finished with value: 0.0394379101917383 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:06:40,045] Trial 120 finished with value: 0.1099909224278834 and parameters: {'model_name': 'VAE', 'batch_size': 214, 'iterations': 7, 'learning_rate': 0.026205385039404425, 'p_miss': 0.09921139498801548}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:06:47,079] Trial 103 finished with value: 0.039607361945102275 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:07:27,331] Trial 105 finished with value: 0.039361124721321555 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:07:29,697] Trial 123 finished with value: 0.09026705261454046 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 6542, 'weights': 'distance'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:07:41,243] Trial 124 finished with value: 0.08577008236866851 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random', 'sample_posterior': True}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:08:24,848] Trial 106 finished with value: 0.03964504512929699 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'arabic'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:10:10,545] Trial 107 finished with value: 0.03921995856033868 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:21:14,853] Trial 108 finished with value: 0.0394029677241765 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:40:12,814] Trial 109 finished with value: 0.039445005913190154 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 21, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:40:17,198] Trial 129 finished with value: 0.060000880009873137 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'ascending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:49:42,397] Trial 110 finished with value: 0.03967398678676789 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 14:59:36,723] Trial 112 finished with value: 0.0392808141128813 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:00:06,312] Trial 113 finished with value: 0.039515127012479556 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:00:06,622] Trial 133 finished with value: 0.10754797919449854 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:07:37,131] Trial 114 finished with value: 0.039557210526039575 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:09:25,746] Trial 115 finished with value: 0.03921215988917614 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:16:47,900] Trial 116 finished with value: 0.039426662981845495 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'ascending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:37:38,978] Trial 117 finished with value: 0.03922383930711406 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:39:56,891] Trial 118 finished with value: 0.039989650627894904 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:43:06,645] Trial 119 finished with value: 0.03966841702547301 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:43:18,447] Trial 140 finished with value: 0.08752129869447266 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 18, 'imputation_order': 'descending', 'sample_posterior': True}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:45:30,214] Trial 122 finished with value: 0.03958411530960291 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:45:31,489] Trial 142 finished with value: 0.1471378966838734 and parameters: {'model_name': 'VAE', 'batch_size': 299, 'iterations': 1, 'learning_rate': 0.03695832976815685, 'p_miss': 0.2132292305882749}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:45:42,849] Trial 121 finished with value: 0.03948646519543292 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:45:51,456] Trial 144 finished with value: 0.06005921258053274 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 18, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:46:25,695] Trial 125 finished with value: 0.03959123879084338 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 21, 'imputation_order': 'ascending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:47:00,157] Trial 126 finished with value: 0.039119370810973934 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 15:48:49,091] Trial 127 finished with value: 0.03930517719771026 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 21, 'imputation_order': 'ascending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:02:34,967] Trial 128 finished with value: 0.03909047867907186 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'ascending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:13:24,810] Trial 130 finished with value: 0.03994037015967847 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 18, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:21:57,829] Trial 145 finished with value: 0.0497881507785973 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 6, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:23:42,299] Trial 131 finished with value: 0.03969654859507503 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 18, 'imputation_order': 'descending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:23:44,844] Trial 152 finished with value: 0.08461154727655887 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3070, 'weights': 'distance'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:33:42,112] Trial 132 finished with value: 0.03956352409256115 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 18, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:34:23,610] Trial 134 finished with value: 0.03967837724265812 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 18, 'imputation_order': 'descending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:41:05,083] Trial 136 finished with value: 0.03949276384840449 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 18, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:51:07,464] Trial 135 finished with value: 0.03946971253602628 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'descending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 16:52:02,068] Trial 137 finished with value: 0.040038679573482526 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 18, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:00:15,845] Trial 150 finished with value: 0.04393231310612928 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 8, 'imputation_order': 'descending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:13:37,809] Trial 138 finished with value: 0.039624273074466546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 18, 'imputation_order': 'descending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:13:55,308] Trial 139 finished with value: 0.04021559261682942 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 18, 'imputation_order': 'descending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:15:19,578] Trial 141 finished with value: 0.039929032419717805 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 18, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:18:06,396] Trial 143 finished with value: 0.03914478925878027 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 18, 'imputation_order': 'roman'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:18:06,843] Trial 163 finished with value: 0.17675017307085134 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:27:14,965] Trial 147 finished with value: 0.03955547721332691 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:27:35,339] Trial 146 finished with value: 0.039110085982482945 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:29:32,110] Trial 148 finished with value: 0.03942806099969666 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 17:46:23,923] Trial 149 finished with value: 0.03917939519848557 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 18:03:17,761] Trial 151 finished with value: 0.039622366230411044 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'descending'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 18:08:33,059] Trial 153 finished with value: 0.039368602829092124 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 80 with value: 0.039066720511836725.
running
[I 2024-09-24 18:18:34,194] Trial 154 finished with value: 0.039061290688899956 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 154 with value: 0.039061290688899956.
running
[I 2024-09-24 18:18:46,871] Trial 171 finished with value: 0.08617863405946442 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman', 'sample_posterior': True}. Best is trial 154 with value: 0.039061290688899956.
running
[I 2024-09-24 18:19:22,093] Trial 155 finished with value: 0.038810564802275724 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 18:19:22,760] Trial 173 finished with value: 0.4307181537574036 and parameters: {'model_name': 'VAE', 'batch_size': 20, 'iterations': 2, 'learning_rate': 0.006777615544224889, 'p_miss': 0.02714794148103447}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 18:22:36,309] Trial 156 finished with value: 0.039466003238158055 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'ascending'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 18:36:10,808] Trial 157 finished with value: 0.039721989413478556 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 18:36:11,438] Trial 158 finished with value: 0.039294389330707516 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'ascending'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 18:45:03,269] Trial 159 finished with value: 0.039466021148298704 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 18:56:59,474] Trial 162 finished with value: 0.03916141458224541 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 18:57:33,128] Trial 161 finished with value: 0.039315506392279695 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 18:57:37,470] Trial 180 finished with value: 0.06048674556637643 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 15, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 18:58:17,736] Trial 160 finished with value: 0.039310590988732616 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 20, 'imputation_order': 'arabic'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 19:00:17,893] Trial 164 finished with value: 0.039960913054199736 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 19:09:04,430] Trial 165 finished with value: 0.03957392973494257 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 19:09:06,412] Trial 184 finished with value: 0.08202219126451227 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1524, 'weights': 'uniform'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 19:09:16,453] Trial 166 finished with value: 0.03919916310829105 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 19:11:11,397] Trial 167 finished with value: 0.03950093821625225 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 19:29:12,945] Trial 168 finished with value: 0.039110574066803634 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 19:46:11,127] Trial 169 finished with value: 0.03953324235574972 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 19:53:21,610] Trial 170 finished with value: 0.04013782478980386 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 19:57:30,307] Trial 177 finished with value: 0.03992834907671681 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 15, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 20:03:21,483] Trial 172 finished with value: 0.03939968139046734 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 20:04:11,241] Trial 174 finished with value: 0.03904463193338907 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 20:04:56,557] Trial 175 finished with value: 0.03937530959397514 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 20:21:02,299] Trial 176 finished with value: 0.0394743917023071 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 20:25:45,783] Trial 178 finished with value: 0.039490884067342566 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 19, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 20:37:19,462] Trial 181 finished with value: 0.039296735975887634 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 20:39:00,470] Trial 182 finished with value: 0.03974699300727271 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 20:39:47,976] Trial 183 finished with value: 0.03938812240170406 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
running
[I 2024-09-24 20:40:30,720] Trial 179 finished with value: 0.03969391957410939 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 20, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 20:48:20,484] Trial 186 finished with value: 0.03949587072488056 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 19, 'imputation_order': 'roman'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 20:48:23,936] Trial 185 finished with value: 0.03954068909528581 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 20:50:33,815] Trial 187 finished with value: 0.03944703212634927 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 21:08:38,107] Trial 188 finished with value: 0.039552644731051176 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 21:24:42,444] Trial 189 finished with value: 0.03997853969961668 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 21:32:15,449] Trial 190 finished with value: 0.03948903845401423 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 21:35:44,056] Trial 191 finished with value: 0.03913430641816674 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 21:42:05,316] Trial 192 finished with value: 0.03969244161935149 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 21:42:22,865] Trial 193 finished with value: 0.039586954056134924 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 21:43:16,571] Trial 194 finished with value: 0.039588504480288174 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 21:58:47,044] Trial 195 finished with value: 0.04008190891040879 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'arabic'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 22:02:55,510] Trial 196 finished with value: 0.039388939899198415 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 19, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 22:17:00,312] Trial 197 finished with value: 0.03972864025104722 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 22:18:44,462] Trial 198 finished with value: 0.03948067055936632 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
[I 2024-09-24 22:19:07,973] Trial 199 finished with value: 0.03974643543817662 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 21, 'imputation_order': 'random'}. Best is trial 155 with value: 0.038810564802275724.
fit
auto fit
auto transform
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
dtype: int64
0.038810564802275724
{'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'random'}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547472d5d0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  1
Best root_mean_squared_error score: -2.4108073968892856
Generation:   4%|▍         | 1/25 [04:54<1:57:42, 294.26s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a9870> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  2
Best root_mean_squared_error score: -2.4108073968892856
Generation:   8%|▊         | 2/25 [05:39<56:40, 147.86s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470c070> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  3
Best root_mean_squared_error score: -2.4108073968892856
Generation:  12%|█▏        | 3/25 [06:29<37:44, 102.93s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547470e410> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  4
Best root_mean_squared_error score: -2.4108073968892856
Generation:  16%|█▌        | 4/25 [07:05<26:46, 76.48s/it] Generation:  5
Best root_mean_squared_error score: -2.4108073968892856
Generation:  20%|██        | 5/25 [10:32<41:16, 123.84s/it]Generation:  6
Best root_mean_squared_error score: -2.4108073968892856
Generation:  24%|██▍       | 6/25 [11:18<30:48, 97.26s/it] WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d6fd60> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  7
Best root_mean_squared_error score: -2.4108073968892856
Generation:  28%|██▊       | 7/25 [16:25<49:47, 165.98s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474730370> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  8
Best root_mean_squared_error score: -2.3778035218099847
Generation:  32%|███▏      | 8/25 [22:43<1:06:05, 233.26s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f607c0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d16140> 

Generation:  9
Best root_mean_squared_error score: -2.3778035218099847
Generation:  36%|███▌      | 9/25 [32:49<1:33:19, 349.96s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467fad720> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  10
Best root_mean_squared_error score: -2.3778035218099847
Generation:  40%|████      | 10/25 [36:44<1:18:33, 314.26s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545bcd53c0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  11
Best root_mean_squared_error score: -2.3778035218099847
Generation:  44%|████▍     | 11/25 [44:57<1:26:06, 369.03s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd7670> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  12
Best root_mean_squared_error score: -2.3778035218099847
Generation:  48%|████▊     | 12/25 [47:44<1:06:37, 307.52s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467977010> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  13
Best root_mean_squared_error score: -2.3778035218099847
Generation:  52%|█████▏    | 13/25 [49:21<48:46, 243.85s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467b4e620> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  14
Best root_mean_squared_error score: -2.3778035218099847
Generation:  56%|█████▌    | 14/25 [51:35<38:35, 210.50s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d14b50> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554745cfc10> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  15
Best root_mean_squared_error score: -2.3778035218099847
Generation:  60%|██████    | 15/25 [58:06<44:09, 264.93s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e36080> 

Generation:  16
Best root_mean_squared_error score: -2.3778035218099847
Generation:  64%|██████▍   | 16/25 [1:08:14<55:16, 368.47s/it]Generation:  17
Best root_mean_squared_error score: -2.3778035218099847
Generation:  68%|██████▊   | 17/25 [1:14:33<49:31, 371.49s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554675026e0> 

Generation:  18
Best root_mean_squared_error score: -2.3778035218099847
Generation:  72%|███████▏  | 18/25 [1:24:43<51:42, 443.16s/it]Generation:  19
Best root_mean_squared_error score: -2.3778035218099847
Generation:  76%|███████▌  | 19/25 [1:27:39<36:17, 362.94s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465132920> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  20
Best root_mean_squared_error score: -2.3778035218099847
Generation:  80%|████████  | 20/25 [1:36:01<33:43, 404.78s/it]Generation:  21
Best root_mean_squared_error score: -2.3778035218099847
Generation:  84%|████████▍ | 21/25 [1:44:27<29:00, 435.16s/it]Generation:  22
Best root_mean_squared_error score: -2.3778035218099847
Generation:  88%|████████▊ | 22/25 [1:49:30<19:46, 395.50s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545bdcf010> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546528f160> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  23
Best root_mean_squared_error score: -2.3778035218099847
Generation:  92%|█████████▏| 23/25 [1:52:14<10:51, 325.78s/it]Generation:  24
Best root_mean_squared_error score: -2.3744494519555714
Generation:  96%|█████████▌| 24/25 [1:58:49<05:46, 346.75s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d4eda0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  25
Best root_mean_squared_error score: -2.359144872539325
Generation: 100%|██████████| 25/25 [2:04:20<00:00, 341.94s/it]Generation: 100%|██████████| 25/25 [2:04:23<00:00, 298.54s/it]
2024-09-25 00:48:48,590 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nosplit_nbytes_bin = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/distributed/worker.py", line 1250, in heartbeat
    response = await retry_operation(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/distributed/utils_comm.py", line 459, in retry_operation
    return await retry(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/distributed/utils_comm.py", line 438, in retry
    return await coro()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/distributed/core.py", line 1256, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/distributed/core.py", line 1015, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:51844 remote=tcp://127.0.0.1:39031>: Stream is closed
2024-09-25 00:48:48,662 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:34389' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-9d779fa107dd0a29a3a90b6bacd04ebf', 'ndarray-970b441435dcd3ea10cfb4a8d98fbc93'} (stimulus_id='handle-worker-cleanup-1727250528.6628559')
Fitted
Pipeline(steps=[('mlpregressor',
                 MLPRegressor(alpha=0.090639388353, early_stopping=True,
                              hidden_layer_sizes=[496, 496, 496],
                              learning_rate='invscaling',
                              learning_rate_init=0.00932729095,
                              n_iter_no_change=32))])
score start
train score: {'explained_var': 0.9870657254950653, 'r2': 0.9869412501010888, 'rmse': 2.1298265608311038}
original test score: {'explained_var': 0.9823566762367244, 'r2': 0.9822775286888924, 'rmse': 2.3181606227673415}
imputed test score: {'explained_var': 0.9823774844190254, 'r2': 0.9822989445113529, 'rmse': 2.316759567509002}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x15535fe77c10>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released 7 days ago.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a91b0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a5210> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a4b80> 

Generation:  1
Best root_mean_squared_error score: -2.8175200129799745
Generation:   4%|▍         | 1/25 [10:02<4:00:54, 602.29s/it]Generation:  2
Best root_mean_squared_error score: -2.8175200129799745
Generation:   8%|▊         | 2/25 [15:21<2:46:56, 435.51s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e2b1c0> 

Generation:  3
Best root_mean_squared_error score: -2.8175200129799745
Generation:  12%|█▏        | 3/25 [25:24<3:07:49, 512.24s/it]Generation:  4
Best root_mean_squared_error score: -2.546289012843667
Generation:  16%|█▌        | 4/25 [30:46<2:32:55, 436.92s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467e2b130> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  5
Best root_mean_squared_error score: -2.546289012843667
Generation:  20%|██        | 5/25 [33:05<1:49:49, 329.48s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1553fe23fb80> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  6
Best root_mean_squared_error score: -2.4980654171572354
Generation:  24%|██▍       | 6/25 [36:27<1:30:37, 286.21s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1553dcf741f0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f26500> 

Generation:  7
Best root_mean_squared_error score: -2.4437188015417193
Generation:  28%|██▊       | 7/25 [46:31<1:57:04, 390.23s/it]Generation:  8
Best root_mean_squared_error score: -2.367206741025009
Generation:  32%|███▏      | 8/25 [50:21<1:36:04, 339.11s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465ce8070> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155452d7e740> 
 Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 751, in fit
    return self._fit(X, y, incremental=False)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 441, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py", line 1621, in _validate_input
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
MLPRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  9
Best root_mean_squared_error score: -2.3631994587310543
Generation:  36%|███▌      | 9/25 [52:52<1:14:45, 280.31s/it]Generation:  10
Best root_mean_squared_error score: -2.2960722002785086
Generation:  40%|████      | 10/25 [55:22<1:00:00, 240.04s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465beeef0> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  11
Best root_mean_squared_error score: -2.28156356751198
Generation:  44%|████▍     | 11/25 [57:46<49:12, 210.87s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1553337123e0> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  12
Best root_mean_squared_error score: -2.28156356751198
Generation:  48%|████▊     | 12/25 [1:00:40<43:14, 199.61s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467b35c60> 
 The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of RandomForestRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mse' instead.

Generation:  13
Best root_mean_squared_error score: -2.28156356751198
Generation:  52%|█████▏    | 13/25 [1:01:39<31:24, 157.07s/it]Generation:  14
Best root_mean_squared_error score: -2.28156356751198
Generation:  56%|█████▌    | 14/25 [1:05:25<32:36, 177.85s/it]Generation:  15
Best root_mean_squared_error score: -2.28156356751198
Generation:  60%|██████    | 15/25 [1:05:35<21:10, 127.00s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f23a90> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

Generation:  16
Best root_mean_squared_error score: -2.28156356751198
Generation:  64%|██████▍   | 16/25 [1:06:00<14:28, 96.53s/it] Generation:  17
Best root_mean_squared_error score: -2.28156356751198
Generation:  68%|██████▊   | 17/25 [1:06:30<10:12, 76.56s/it]Generation:  18
Best root_mean_squared_error score: -2.28156356751198
Generation:  72%|███████▏  | 18/25 [1:06:45<06:46, 58.05s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f22b60> 

Generation:  19
Best root_mean_squared_error score: -2.28156356751198
Generation:  76%|███████▌  | 19/25 [1:16:52<22:16, 222.77s/it]Generation:  20
Best root_mean_squared_error score: -2.28156356751198
Generation:  80%|████████  | 20/25 [1:20:32<18:30, 222.01s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155452700850> 
 The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546576b250> 

Generation:  21
Best root_mean_squared_error score: -2.28156356751198
Generation:  84%|████████▍ | 21/25 [1:30:39<22:30, 337.61s/it]Generation:  22
Best root_mean_squared_error score: -2.28156356751198
Generation:  88%|████████▊ | 22/25 [1:32:52<13:48, 276.19s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546516ca30> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554523b1ff0> 

Generation:  23
Best root_mean_squared_error score: -2.28156356751198
Generation:  92%|█████████▏| 23/25 [1:42:59<12:30, 375.47s/it]Generation:  24
Best root_mean_squared_error score: -2.28156356751198
Generation:  96%|█████████▌| 24/25 [1:43:31<04:32, 272.49s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15546565d4e0> 
 The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of ExtraTreesRegressor must be a str among {'friedman_mse', 'poisson', 'absolute_error', 'squared_error'}. Got 'mae' instead.

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554523adf90> 

Generation:  25
Best root_mean_squared_error score: -2.28156356751198
Generation: 100%|██████████| 25/25 [1:53:39<00:00, 372.99s/it]Generation: 100%|██████████| 25/25 [1:53:39<00:00, 272.78s/it]
2024-09-25 02:42:49,945 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:33715' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-9d779fa107dd0a29a3a90b6bacd04ebf', 'DataFrame-d79609e5ff881730852a4a11adc2e4f7'} (stimulus_id='handle-worker-cleanup-1727257369.9449954')
Fitted
Pipeline(steps=[('knnimputer', KNNImputer(n_neighbors=79, weights='distance')),
                ('lgbmregressor',
                 LGBMRegressor(max_depth=7, n_estimators=98, n_jobs=1,
                               num_leaves=142, verbose=-1))])
transform worked
try transform
transform worked
score start
train score: {'explained_var': 0.9935914068673276, 'r2': 0.9935914068673276, 'rmse': 1.492020487465259}
test score: {'explained_var': 0.9837262095414805, 'r2': 0.9837258031630758, 'rmse': 2.2214224965913085}
original test score: {'explained_var': 0.9839012735616062, 'r2': 0.9839007916595796, 'rmse': 2.209447282674853}
score end
197
lvl
0.01
type
MCAR
num_run
2
reg_full
finished
all finished
full run takes
20.15232966873381
hours
DONE
