Run: 49
/cm/local/apps/slurm/var/spool/job1069597/slurm_script: line 27: 
pip install -e tpot2
pip install -r tpot2/ImputerExperiments/requirements_.txt
: No such file or directory
RunStart
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
starting loops
../data/c/40701/40701.pkl
working on 
../data/c/40701/class_full_MCAR_0.01_3
1.7974774837493896
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2024-11-24 01:39:44,871] A new study created in memory with name: no-name-3f09845e-a8c2-4737-96a1-8e96c22355bb
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
running
[I 2024-11-24 01:39:45,079] Trial 5 finished with value: 0.5131509335350433 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 5 with value: 0.5131509335350433.
running
[I 2024-11-24 01:39:45,285] Trial 14 finished with value: 0.5131509335350433 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 5 with value: 0.5131509335350433.
running
[I 2024-11-24 01:39:45,438] Trial 4 finished with value: 0.22923831036741968 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 4 with value: 0.22923831036741968.
running
[I 2024-11-24 01:39:45,691] Trial 16 finished with value: 0.22923831036741968 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'median'}. Best is trial 4 with value: 0.22923831036741968.
running
[I 2024-11-24 01:39:45,929] Trial 6 finished with value: 0.39405049707825474 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 4 with value: 0.22923831036741968.
running
[I 2024-11-24 01:39:46,282] Trial 20 finished with value: 0.21607588624938784 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 20 with value: 0.21607588624938784.
running
[I 2024-11-24 01:39:49,053] Trial 3 finished with value: 0.18572505049059285 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 198, 'weights': 'distance'}. Best is trial 3 with value: 0.18572505049059285.
running
[I 2024-11-24 01:39:49,729] Trial 8 finished with value: 0.1983311758743012 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 1062, 'weights': 'uniform'}. Best is trial 3 with value: 0.18572505049059285.
running
[I 2024-11-24 01:39:49,982] Trial 19 finished with value: 0.19265445009466098 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 638, 'weights': 'uniform'}. Best is trial 3 with value: 0.18572505049059285.
running
[I 2024-11-24 01:39:54,763] Trial 15 finished with value: 0.4778069929855386 and parameters: {'model_name': 'GAIN', 'batch_size': 3, 'hint_rate': 0.10282288526695152, 'alpha': 41, 'iterations': 2, 'learning_rate': 0.0018198064922988623, 'p_miss': 0.28986386521131685}. Best is trial 3 with value: 0.18572505049059285.
running
[I 2024-11-24 01:39:55,521] Trial 22 finished with value: 0.24553568402222115 and parameters: {'model_name': 'VAE', 'batch_size': 7, 'iterations': 2, 'learning_rate': 0.05269289912425104, 'p_miss': 0.0914986990683027}. Best is trial 3 with value: 0.18572505049059285.
running
[I 2024-11-24 01:40:00,251] Trial 26 finished with value: 0.18550990952066612 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 12, 'weights': 'distance'}. Best is trial 26 with value: 0.18550990952066612.
running
[I 2024-11-24 01:40:05,945] Trial 27 finished with value: 0.18575458542439657 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 203, 'weights': 'distance'}. Best is trial 26 with value: 0.18550990952066612.
running
[I 2024-11-24 01:40:08,019] Trial 2 finished with value: 0.5071674836299029 and parameters: {'model_name': 'GAIN', 'batch_size': 886, 'hint_rate': 0.412696760264342, 'alpha': 14, 'iterations': 4, 'learning_rate': 0.0008047233288632302, 'p_miss': 0.045852808036943755}. Best is trial 26 with value: 0.18550990952066612.
running
[I 2024-11-24 01:40:08,733] Trial 10 finished with value: 0.16866163576383117 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 3, 'imputation_order': 'arabic', 'sample_posterior': False}. Best is trial 10 with value: 0.16866163576383117.
running
[I 2024-11-24 01:40:18,138] Trial 11 finished with value: 0.16906875512302347 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 13, 'imputation_order': 'random'}. Best is trial 10 with value: 0.16866163576383117.
running
[I 2024-11-24 01:40:27,218] Trial 18 finished with value: 0.47874140183258496 and parameters: {'model_name': 'GAIN', 'batch_size': 9, 'hint_rate': 0.4913793594515768, 'alpha': 42, 'iterations': 78, 'learning_rate': 0.00018502914901857614, 'p_miss': 0.2765713546806772}. Best is trial 10 with value: 0.16866163576383117.
running
[I 2024-11-24 01:40:31,605] Trial 30 finished with value: 0.16992954716940287 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 2, 'imputation_order': 'arabic', 'sample_posterior': False}. Best is trial 10 with value: 0.16866163576383117.
running
[I 2024-11-24 01:40:37,300] Trial 28 finished with value: 0.16885030085111977 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'random'}. Best is trial 10 with value: 0.16866163576383117.
running
[I 2024-11-24 01:41:00,068] Trial 33 finished with value: 0.1687512603942618 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 15, 'imputation_order': 'random'}. Best is trial 10 with value: 0.16866163576383117.
running
[I 2024-11-24 01:41:01,207] Trial 12 finished with value: 0.16864227011262792 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 7, 'imputation_order': 'random', 'sample_posterior': False}. Best is trial 12 with value: 0.16864227011262792.
running
[I 2024-11-24 01:41:05,252] Trial 34 finished with value: 0.16875055680023504 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 20, 'imputation_order': 'ascending'}. Best is trial 12 with value: 0.16864227011262792.
running
[I 2024-11-24 01:41:15,647] Trial 29 finished with value: 0.16887183916487383 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'random', 'sample_posterior': False}. Best is trial 12 with value: 0.16864227011262792.
running
[I 2024-11-24 01:41:23,210] Trial 7 finished with value: 0.23803325824501456 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 9, 'imputation_order': 'arabic', 'sample_posterior': True}. Best is trial 12 with value: 0.16864227011262792.
running
[I 2024-11-24 01:41:38,022] Trial 31 finished with value: 0.16864389600686866 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 11, 'imputation_order': 'random', 'sample_posterior': False}. Best is trial 12 with value: 0.16864227011262792.
running
[I 2024-11-24 01:41:40,579] Trial 21 finished with value: 0.23325522499467458 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 12, 'imputation_order': 'arabic', 'sample_posterior': True}. Best is trial 12 with value: 0.16864227011262792.
running
[I 2024-11-24 01:41:50,090] Trial 32 finished with value: 0.168323239999386 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 11, 'imputation_order': 'arabic', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 01:42:00,229] Trial 39 finished with value: 0.18295482549334258 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 2, 'imputation_order': 'ascending'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 01:42:14,268] Trial 36 finished with value: 0.16888571682247128 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 4, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 01:42:20,943] Trial 37 finished with value: 0.16867540244793122 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 4, 'imputation_order': 'ascending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 01:45:58,897] Trial 23 finished with value: 0.4917548244244688 and parameters: {'model_name': 'GAIN', 'batch_size': 29, 'hint_rate': 0.6521262560540687, 'alpha': 57, 'iterations': 504, 'learning_rate': 0.00012683186107948662, 'p_miss': 0.14427174034662213}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:05:19,496] Trial 9 finished with value: 0.24385943344525823 and parameters: {'model_name': 'VAE', 'batch_size': 488, 'iterations': 369, 'learning_rate': 0.00012775988409137882, 'p_miss': 0.23123480106520944}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:18:25,328] Trial 35 finished with value: 0.18691355831631257 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 2, 'imputation_order': 'roman'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:21:03,213] Trial 48 finished with value: 0.16850955696712755 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 7, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:26:39,650] Trial 38 finished with value: 0.17571643164287243 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 4, 'imputation_order': 'ascending'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:30:02,427] Trial 17 finished with value: 0.17191018934931968 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 6, 'imputation_order': 'roman'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:31:48,926] Trial 43 finished with value: 0.17446537922293315 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'most_frequent', 'n_nearest_features': 6, 'imputation_order': 'descending'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:33:07,749] Trial 13 finished with value: 0.1717233959524173 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 7, 'imputation_order': 'arabic'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:40:11,132] Trial 46 finished with value: 0.17041401528308708 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 8, 'imputation_order': 'descending'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:43:08,799] Trial 1 finished with value: 0.2275666456251484 and parameters: {'model_name': 'VAE', 'batch_size': 6, 'iterations': 1356, 'learning_rate': 0.0001674414172785931, 'p_miss': 0.061877859215971026}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 02:54:50,588] Trial 47 finished with value: 0.17217940983923138 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'constant', 'n_nearest_features': 7, 'imputation_order': 'descending'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 03:53:30,462] Trial 0 finished with value: 0.45636440139350076 and parameters: {'model_name': 'GAIN', 'batch_size': 5, 'hint_rate': 0.08937772884461131, 'alpha': 38, 'iterations': 5766, 'learning_rate': 0.036117804642177974, 'p_miss': 0.2801563365735348}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 03:54:56,984] Trial 57 finished with value: 0.21792418211597392 and parameters: {'model_name': 'VAE', 'batch_size': 105, 'iterations': 22, 'learning_rate': 0.012134811031510238, 'p_miss': 0.19666759636444592}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 03:56:21,314] Trial 58 finished with value: 0.16864389600686866 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 11, 'imputation_order': 'random', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 03:57:44,540] Trial 59 finished with value: 0.16864389600686866 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 11, 'imputation_order': 'random', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 03:58:44,962] Trial 60 finished with value: 0.25227203447572666 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 20, 'learning_rate': 0.008707581870785908, 'p_miss': 0.1226532048422187}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:00:21,334] Trial 61 finished with value: 0.16858651849499684 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 14, 'imputation_order': 'random', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:01:57,917] Trial 62 finished with value: 0.16843204808805562 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 15, 'imputation_order': 'random', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:17:32,428] Trial 24 finished with value: 0.22032630651685076 and parameters: {'model_name': 'VAE', 'batch_size': 33, 'iterations': 3322, 'learning_rate': 0.00029610445609464073, 'p_miss': 0.046289087752782065}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:20:56,509] Trial 64 finished with value: 0.509751925244448 and parameters: {'model_name': 'GAIN', 'batch_size': 168, 'hint_rate': 0.9824624495818524, 'alpha': 96, 'iterations': 131, 'learning_rate': 0.006320823674132423, 'p_miss': 0.19751626547780543}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:22:41,986] Trial 65 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:24:28,434] Trial 66 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:26:02,974] Trial 67 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:28:01,831] Trial 68 finished with value: 0.19071945117692404 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 17, 'imputation_order': 'descending'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:29:42,995] Trial 69 finished with value: 0.1687322663263317 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 17, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:31:21,225] Trial 70 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:31:22,388] Trial 71 finished with value: 0.39405049707825474 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:33:08,180] Trial 72 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:33:13,674] Trial 73 finished with value: 0.21607588624938784 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3642, 'weights': 'uniform'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:33:17,983] Trial 74 finished with value: inf and parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.9748180494255727, 'alpha': 97, 'iterations': 12, 'learning_rate': 0.0007972892889055705, 'p_miss': 0.021376694939974045}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:35:00,799] Trial 75 finished with value: 0.1687322663263317 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 17, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:36:44,427] Trial 76 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:38:24,393] Trial 77 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:40:06,933] Trial 78 finished with value: 0.16867718413124191 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 18, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:41:42,464] Trial 79 finished with value: 0.1683964801680265 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 14, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:41:42,849] Trial 80 finished with value: 0.21607588624938784 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:43:14,475] Trial 81 finished with value: 0.1685433305361743 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 13, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:44:51,137] Trial 82 finished with value: 0.1683964801680265 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 14, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:44:58,301] Trial 83 finished with value: 0.21151556244184871 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 3179, 'weights': 'distance'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:46:37,639] Trial 84 finished with value: 0.24255537971732283 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 14, 'imputation_order': 'arabic', 'sample_posterior': True}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:48:12,143] Trial 85 finished with value: 0.16867718413124191 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 18, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:49:48,530] Trial 86 finished with value: 0.1684984805526688 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 15, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:51:24,233] Trial 87 finished with value: 0.1685433305361743 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 13, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:52:57,161] Trial 88 finished with value: 0.16856883192863908 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 14, 'imputation_order': 'arabic', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:54:36,636] Trial 89 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:56:33,297] Trial 90 finished with value: 0.1915739676579067 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'constant', 'n_nearest_features': 18, 'imputation_order': 'descending'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:56:38,309] Trial 91 finished with value: 0.24172077194503866 and parameters: {'model_name': 'VAE', 'batch_size': 102, 'iterations': 1, 'learning_rate': 0.08766460626770037, 'p_miss': 0.19016030798661432}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 04:58:28,514] Trial 92 finished with value: 0.24397465914293584 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 15, 'imputation_order': 'arabic', 'sample_posterior': True}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:04:20,678] Trial 51 finished with value: 0.21829698601790243 and parameters: {'model_name': 'VAE', 'batch_size': 80, 'iterations': 5201, 'learning_rate': 0.028048173575027296, 'p_miss': 0.010036455707861464}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:14:08,506] Trial 94 finished with value: 0.5374844823403957 and parameters: {'model_name': 'GAIN', 'batch_size': 273, 'hint_rate': 0.7285571602945651, 'alpha': 3, 'iterations': 359, 'learning_rate': 0.002817037034145111, 'p_miss': 0.243557442037739}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:15:40,429] Trial 95 finished with value: 0.16856824821885558 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'median', 'n_nearest_features': 12, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:16:35,422] Trial 41 finished with value: 0.2186533412306117 and parameters: {'model_name': 'VAE', 'batch_size': 288, 'iterations': 3762, 'learning_rate': 0.06656359857740157, 'p_miss': 0.18568210403759644}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:17:33,774] Trial 96 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:18:28,821] Trial 97 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:19:02,726] Trial 99 finished with value: 0.16879755516331924 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'constant', 'n_nearest_features': 17, 'imputation_order': 'descending'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:19:30,558] Trial 98 finished with value: 0.1684153325834546 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 16, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:21:06,801] Trial 100 finished with value: 0.16871205598730152 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 19, 'imputation_order': 'descending', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:21:07,930] Trial 102 finished with value: 0.39405049707825474 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'most_frequent'}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:21:23,349] Trial 55 finished with value: 0.2777919677263937 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 5680, 'learning_rate': 0.03277985418161491, 'p_miss': 0.1844275654124291}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:21:35,695] Trial 101 finished with value: 0.16845426093385987 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 19, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 32 with value: 0.168323239999386.
running
[I 2024-11-24 05:23:05,199] Trial 103 finished with value: 0.16831576654534958 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 14, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:23:08,875] Trial 104 finished with value: 0.16843170113502273 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 13, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:23:17,487] Trial 105 finished with value: 0.16856718755408173 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'constant', 'n_nearest_features': 13, 'imputation_order': 'arabic', 'sample_posterior': False}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:24:48,352] Trial 106 finished with value: 0.16843170113502273 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 13, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:25:00,113] Trial 107 finished with value: 0.1683244780319628 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 15, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:25:05,371] Trial 110 finished with value: 0.20793814453184928 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2042, 'weights': 'uniform'}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:25:13,374] Trial 108 finished with value: 0.1683244780319628 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 15, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:25:46,323] Trial 112 finished with value: 0.16843233788874185 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 14, 'imputation_order': 'roman'}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:26:57,763] Trial 109 finished with value: 0.24109376403173988 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 15, 'imputation_order': 'descending', 'sample_posterior': True}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:27:09,971] Trial 111 finished with value: 0.23875118850929405 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 14, 'imputation_order': 'roman', 'sample_posterior': True}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:27:56,122] Trial 113 finished with value: 0.2391423214443896 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 15, 'imputation_order': 'roman', 'sample_posterior': True}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:28:24,442] Trial 114 finished with value: 0.16836189460610915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 12, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:28:38,396] Trial 115 finished with value: 0.16836189460610915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 12, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:29:33,405] Trial 116 finished with value: 0.16836189460610915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 12, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:29:50,962] Trial 118 finished with value: 0.1844872149830345 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 103 with value: 0.16831576654534958.
running
[I 2024-11-24 05:29:51,998] Trial 117 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:29:57,035] Trial 121 finished with value: 0.5023235015935791 and parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.2895678679509869, 'alpha': 70, 'iterations': 7, 'learning_rate': 0.0005463906812268934, 'p_miss': 0.11159220309131318}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:30:51,916] Trial 49 finished with value: 0.2185743155892071 and parameters: {'model_name': 'VAE', 'batch_size': 89, 'iterations': 7399, 'learning_rate': 0.04407376929920995, 'p_miss': 0.1901824982911008}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:31:00,897] Trial 119 finished with value: 0.18960482155523362 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 12, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:31:24,826] Trial 122 finished with value: 0.16843025028382272 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:31:25,134] Trial 125 finished with value: 0.5131509335350433 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'constant'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:31:26,597] Trial 120 finished with value: 0.16836189460610915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 12, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:32:06,237] Trial 123 finished with value: 0.16843025028382272 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:32:07,218] Trial 52 finished with value: 0.2184344025019888 and parameters: {'model_name': 'VAE', 'batch_size': 81, 'iterations': 7317, 'learning_rate': 0.039255465172686584, 'p_miss': 0.19145320402637744}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:32:18,144] Trial 124 finished with value: 0.16843025028382272 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:32:35,414] Trial 126 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:32:54,771] Trial 127 finished with value: 0.16836189460610915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 12, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:33:34,108] Trial 128 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:33:37,397] Trial 129 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:34:14,139] Trial 130 finished with value: 0.16836189460610915 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 12, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:34:19,217] Trial 135 finished with value: 0.20873492024233467 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2151, 'weights': 'uniform'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:35:26,093] Trial 133 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:36:17,171] Trial 136 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:38:38,230] Trial 138 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:40:47,230] Trial 139 finished with value: 0.16861035708014266 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 05:42:45,624] Trial 40 finished with value: 0.21791780146055212 and parameters: {'model_name': 'VAE', 'batch_size': 281, 'iterations': 4995, 'learning_rate': 0.05578237833616957, 'p_miss': 0.1756706535761852}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:03:58,589] Trial 53 finished with value: 0.21863560387531988 and parameters: {'model_name': 'VAE', 'batch_size': 93, 'iterations': 7934, 'learning_rate': 0.06528870526391754, 'p_miss': 0.012497525554123451}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:21:34,777] Trial 63 finished with value: 0.5215693114427913 and parameters: {'model_name': 'GAIN', 'batch_size': 104, 'hint_rate': 0.9324886865178577, 'alpha': 91, 'iterations': 9443, 'learning_rate': 0.000622573215992135, 'p_miss': 0.19341949251120974}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:27:28,766] Trial 132 finished with value: 0.16932237066729 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:28:02,757] Trial 56 finished with value: 0.21817566642146957 and parameters: {'model_name': 'VAE', 'batch_size': 86, 'iterations': 7956, 'learning_rate': 0.03466048007909959, 'p_miss': 0.18303807412658135}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:29:35,024] Trial 131 finished with value: 0.169571263583082 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:29:39,165] Trial 134 finished with value: 0.1706253835855059 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:29:43,801] Trial 50 finished with value: 0.21850462588451952 and parameters: {'model_name': 'VAE', 'batch_size': 78, 'iterations': 8167, 'learning_rate': 0.04014797930131723, 'p_miss': 0.011005975188006833}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:30:05,494] Trial 144 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:30:27,291] Trial 145 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:31:14,787] Trial 137 finished with value: 0.17037672201019982 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:31:17,538] Trial 146 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:31:20,294] Trial 147 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:31:23,830] Trial 148 finished with value: 0.16827436399038642 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:31:42,171] Trial 149 finished with value: 0.16861035708014266 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:31:53,645] Trial 150 finished with value: 0.16861035708014266 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:32:37,184] Trial 151 finished with value: 0.16861035708014266 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:32:40,723] Trial 152 finished with value: 0.16861035708014266 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:32:41,993] Trial 153 finished with value: 0.16863184198547496 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'ascending', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:32:43,434] Trial 154 finished with value: 0.16863184198547496 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'ascending', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:33:08,433] Trial 155 finished with value: 0.16863184198547496 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 8, 'imputation_order': 'ascending', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:33:15,968] Trial 160 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:33:23,981] Trial 156 finished with value: 0.16873623647403563 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 9, 'imputation_order': 'ascending', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:33:44,285] Trial 161 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:33:50,235] Trial 162 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:33:59,657] Trial 163 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:20,091] Trial 164 finished with value: 0.16859082718482638 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 7, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:20,505] Trial 157 finished with value: 0.1686003009105483 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:21,480] Trial 159 finished with value: 0.16831281995920166 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 7, 'imputation_order': 'roman', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:25,633] Trial 165 finished with value: 0.16859082718482638 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 7, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:26,117] Trial 158 finished with value: 0.16873623647403563 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'most_frequent', 'n_nearest_features': 9, 'imputation_order': 'ascending', 'sample_posterior': False}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:26,454] Trial 170 finished with value: 0.21607588624938784 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:26,680] Trial 171 finished with value: 0.21607588624938784 and parameters: {'model_name': 'SimpleImputer', 'strategy': 'mean'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:36,978] Trial 166 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:58,970] Trial 168 finished with value: 0.1686445996050736 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:34:59,372] Trial 167 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:00,773] Trial 169 finished with value: 0.1686445996050736 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:02,520] Trial 172 finished with value: 0.1686445996050736 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:04,875] Trial 173 finished with value: 0.1686445996050736 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:13,788] Trial 174 finished with value: 0.1686445996050736 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:21,472] Trial 180 finished with value: 0.20922484067573185 and parameters: {'model_name': 'KNNImputer', 'n_neighbors': 2691, 'weights': 'distance'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:22,329] Trial 175 finished with value: 0.47504126883952214 and parameters: {'model_name': 'GAIN', 'batch_size': 15, 'hint_rate': 0.27316401919058075, 'alpha': 74, 'iterations': 41, 'learning_rate': 0.01923191170270533, 'p_miss': 0.22883685484430794}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:40,908] Trial 176 finished with value: 0.1686445996050736 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 10, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:41,408] Trial 177 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:41,709] Trial 178 finished with value: 0.1684863094673686 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:44,288] Trial 179 finished with value: 0.1684863094673686 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:35:59,997] Trial 181 finished with value: 0.1684863094673686 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:00,704] Trial 182 finished with value: 0.1684863094673686 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:21,081] Trial 184 finished with value: 0.16837525521961821 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 11, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:21,603] Trial 185 finished with value: 0.16837525521961821 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 11, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:22,130] Trial 183 finished with value: 0.1684863094673686 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'median', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:23,064] Trial 186 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:38,397] Trial 187 finished with value: 0.16837525521961821 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 11, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:39,529] Trial 188 finished with value: 0.16837525521961821 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 11, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:57,353] Trial 191 finished with value: 0.16845510557062798 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:58,137] Trial 189 finished with value: 0.16854792327795842 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'random'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:36:59,268] Trial 190 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:37:00,014] Trial 192 finished with value: 0.16854792327795842 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'random'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:37:14,578] Trial 193 finished with value: 0.16867929809320942 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
running
[I 2024-11-24 06:37:42,967] Trial 196 finished with value: 0.16829455887378075 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'Ridge', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 06:37:51,548] Trial 194 finished with value: 0.18320590932147365 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'random'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 06:38:02,751] Trial 197 finished with value: 0.1844164216008568 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 06:38:03,941] Trial 198 finished with value: 0.1844164216008568 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 8, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 06:38:05,349] Trial 195 finished with value: 0.1834128466567666 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 06:38:10,035] Trial 199 finished with value: 0.1834128466567666 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'KNN', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 06:38:31,197] Trial 140 finished with value: 0.17123421887658047 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 06:39:18,166] Trial 141 finished with value: 0.17051372883614474 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 06:52:45,843] Trial 54 finished with value: 0.2677006047337981 and parameters: {'model_name': 'VAE', 'batch_size': 1, 'iterations': 9566, 'learning_rate': 0.04320071030444226, 'p_miss': 0.019431712736773687}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 06:54:05,093] Trial 142 finished with value: 0.17063298388872117 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 07:00:50,895] Trial 45 finished with value: 0.22017229488716555 and parameters: {'model_name': 'VAE', 'batch_size': 212, 'iterations': 6699, 'learning_rate': 0.08735625766679808, 'p_miss': 0.1722973023460798}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 07:02:34,646] Trial 42 finished with value: 0.22755125718759248 and parameters: {'model_name': 'VAE', 'batch_size': 296, 'iterations': 6879, 'learning_rate': 0.09629221621041174, 'p_miss': 0.1805131605157989}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 07:03:41,390] Trial 143 finished with value: 0.17000916119556078 and parameters: {'model_name': 'IterativeImputer', 'estimator': 'RFR', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman'}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 07:03:52,488] Trial 93 finished with value: 0.5124049107578502 and parameters: {'model_name': 'GAIN', 'batch_size': 236, 'hint_rate': 0.6869757975555304, 'alpha': 1, 'iterations': 9947, 'learning_rate': 0.0030476667641759587, 'p_miss': 0.23088974751300367}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 07:08:21,285] Trial 44 finished with value: 0.21913294600192018 and parameters: {'model_name': 'VAE', 'batch_size': 235, 'iterations': 8849, 'learning_rate': 0.0903759606614994, 'p_miss': 0.16456330438077085}. Best is trial 117 with value: 0.16827436399038642.
[I 2024-11-24 07:19:14,538] Trial 25 finished with value: 0.2233947871956584 and parameters: {'model_name': 'VAE', 'batch_size': 857, 'iterations': 9532, 'learning_rate': 0.09972392048671769, 'p_miss': 0.022856782172494067}. Best is trial 117 with value: 0.16827436399038642.
fit
auto fit
auto transform
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
dtype: int64
0.16827436399038642
{'model_name': 'IterativeImputer', 'estimator': 'Bayesian', 'initial_strategy': 'mean', 'n_nearest_features': 9, 'imputation_order': 'roman', 'sample_posterior': False}
running experiment 2/3 - Does reconstruction give good automl predictions
Start est fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474714b20> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474731c00> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746a0f10> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  1
Best f1_score score: 0.8724666772741809
Generation:   4%|▍         | 1/25 [00:12<04:59, 12.49s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474710a60> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  2
Best f1_score score: 0.8772606657333878
Generation:   8%|▊         | 2/25 [03:14<43:04, 112.38s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474730b50> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  3
Best f1_score score: 0.8877845340415467
Generation:  12%|█▏        | 3/25 [05:56<49:31, 135.05s/it]Generation:  4
Best f1_score score: 0.892346819999927
Generation:  16%|█▌        | 4/25 [06:21<32:01, 91.52s/it] WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474735720> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  5
Best f1_score score: 0.8936569371973031
Generation:  20%|██        | 5/25 [07:55<30:47, 92.39s/it]Generation:  6
Best f1_score score: 0.9017911506828538
Generation:  24%|██▍       | 6/25 [08:25<22:31, 71.15s/it]Generation:  7
Best f1_score score: 0.9017911506828538
Generation:  28%|██▊       | 7/25 [10:00<23:40, 78.92s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467f07a30> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  8
Best f1_score score: 0.905169691781835
Generation:  32%|███▏      | 8/25 [10:27<17:38, 62.27s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155467c10c70> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  9
Best f1_score score: 0.9056877854012739
Generation:  36%|███▌      | 9/25 [10:47<13:04, 49.06s/it]Generation:  10
Best f1_score score: 0.9068284263921698
Generation:  40%|████      | 10/25 [11:59<14:05, 56.34s/it]Generation:  11
Best f1_score score: 0.9074012989789345
Generation:  44%|████▍     | 11/25 [12:19<10:32, 45.19s/it]Generation:  12
Best f1_score score: 0.9074012989789345
Generation:  48%|████▊     | 12/25 [12:43<08:25, 38.85s/it]Generation:  13
Best f1_score score: 0.9074012989789345
Generation:  52%|█████▏    | 13/25 [13:05<06:42, 33.58s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554650acd60> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  14
Best f1_score score: 0.9074012989789345
Generation:  56%|█████▌    | 14/25 [13:22<05:15, 28.72s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465aab940> 
 The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474714670> 
 The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead. 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1466, in wrapper
    estimator._validate_params()
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'min_samples_split' parameter of DecisionTreeClassifier must be an int in the range [2, inf) or a float in the range (0.0, 1.0]. Got 1 instead.

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554679e4f40> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  15
Best f1_score score: 0.9074012989789345
Generation:  60%|██████    | 15/25 [13:45<04:28, 26.86s/it]Generation:  16
Best f1_score score: 0.9079581627527034
Generation:  64%|██████▍   | 16/25 [14:34<05:03, 33.70s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554746f4820> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554678a6110> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  17
Best f1_score score: 0.9079581627527034
Generation:  68%|██████▊   | 17/25 [14:49<03:42, 27.79s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465b56a10> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  18
Best f1_score score: 0.9079581627527034
Generation:  72%|███████▏  | 18/25 [15:04<02:47, 23.95s/it]Generation:  19
Best f1_score score: 0.9124173246955796
Generation:  76%|███████▌  | 19/25 [15:25<02:18, 23.12s/it]Generation:  20
Best f1_score score: 0.9124173246955796
Generation:  80%|████████  | 20/25 [15:38<01:41, 20.23s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465564a90> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  21
Best f1_score score: 0.9124173246955796
Generation:  84%|████████▍ | 21/25 [15:50<01:10, 17.55s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465568460> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  22
Best f1_score score: 0.9124173246955796
Generation:  88%|████████▊ | 22/25 [17:07<01:47, 35.68s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155465460070> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  23
Best f1_score score: 0.9124173246955796
Generation:  92%|█████████▏| 23/25 [17:26<01:00, 30.42s/it]Generation:  24
Best f1_score score: 0.9146418144526658
Generation:  96%|█████████▌| 24/25 [17:46<00:27, 27.49s/it]Generation:  25
Best f1_score score: 0.9146418144526658
Generation: 100%|██████████| 25/25 [18:12<00:00, 26.88s/it]Generation: 100%|██████████| 25/25 [18:16<00:00, 43.84s/it]
2024-11-24 07:37:38,510 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:46767' caused the cluster to lose scattered data, which can't be recovered: {'ndarray-3bf46d47a1fced1c19e2291888a0d027', 'ndarray-f70cb5088a4b38b195da3685bce072b9'} (stimulus_id='handle-worker-cleanup-1732462658.5100074')
Fitted
Pipeline(steps=[('lgbmclassifier',
                 LGBMClassifier(boosting_type='dart', max_depth=7,
                                n_estimators=75, n_jobs=1, num_leaves=159,
                                verbose=-1))])
score start
train score: {'auroc': 0.9929256592256608, 'accuracy': 0.97975, 'balanced_accuracy': 0.9291830191125535, 'logloss': 0.08980801964180131, 'f1': 0.9557086069249594}
original test score: {'auroc': 0.9147697718772447, 'accuracy': 0.96, 'balanced_accuracy': 0.8729761639379453, 'logloss': 0.154189120024305, 'f1': 0.9091932730376666}
imputed test score: {'auroc': 0.9121359984808329, 'accuracy': 0.959, 'balanced_accuracy': 0.8694300646471651, 'logloss': 0.1571719249871014, 'f1': 0.906605709807995}
score end
check intended
EXP2 Finished
running experiment 3/3 - What is the best automl settings?
<tpot2.search_spaces.pipelines.sequential.SequentialPipeline object at 0x1554350145b0>
Start tpot fit
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
Version 0.1.7a0 of tpot2 is outdated. Version 0.1.8a0 was released Tuesday September 17, 2024.
  0%|          | 0/25 [00:00<?, ?it/s]Generation:   0%|          | 0/25 [00:00<?, ?it/s]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474cd1630> 

Generation:  1
Best f1_score score: 0.8841466410560992
Generation:   4%|▍         | 1/25 [10:01<4:00:46, 601.92s/it]Generation:  2
Best f1_score score: 0.8872913141866906
Generation:   8%|▊         | 2/25 [10:15<1:38:00, 255.67s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d379a0> 
 Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1223, in fit
    X, y = self._validate_data(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 650, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1301, in check_X_y
    X = check_array(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1064, in check_array
    _assert_all_finite(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Generation:  3
Best f1_score score: 0.8885673710037107
Generation:  12%|█▏        | 3/25 [11:58<1:08:12, 186.00s/it]Generation:  4
Best f1_score score: 0.9007733759384215
Generation:  16%|█▌        | 4/25 [12:22<42:44, 122.11s/it]  Generation:  5
Best f1_score score: 0.9007733759384215
Generation:  20%|██        | 5/25 [12:56<30:05, 90.28s/it] WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474d19c30> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  6
Best f1_score score: 0.9022367588776413
Generation:  24%|██▍       | 6/25 [13:10<20:22, 64.33s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155474597970> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155456b6d570> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15547507a920> 

Generation:  7
Best f1_score score: 0.9022367588776413
Generation:  28%|██▊       | 7/25 [23:15<1:12:19, 241.08s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545720d7e0> 

Generation:  8
Best f1_score score: 0.9096483023129448
Generation:  32%|███▏      | 8/25 [33:19<1:41:05, 356.81s/it]Generation:  9
Best f1_score score: 0.9096483023129448
Generation:  36%|███▌      | 9/25 [33:29<1:06:11, 248.21s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155456fbf610> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545712c250> 

Generation:  10
Best f1_score score: 0.9096483023129448
Generation:  40%|████      | 10/25 [43:36<1:29:43, 358.92s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554551aa200> 

Generation:  11
Best f1_score score: 0.9096483023129448
Generation:  44%|████▍     | 11/25 [53:42<1:41:25, 434.71s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155455008100> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554551631c0> 

Generation:  12
Best f1_score score: 0.9096483023129448
Generation:  48%|████▊     | 12/25 [1:03:49<1:45:32, 487.09s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155454df20b0> 

Generation:  13
Best f1_score score: 0.9096483023129448
Generation:  52%|█████▏    | 13/25 [1:13:55<1:44:36, 523.08s/it]Generation:  14
Best f1_score score: 0.9096483023129448
Generation:  56%|█████▌    | 14/25 [1:17:29<1:18:48, 429.84s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554524e84f0> 

Generation:  15
Best f1_score score: 0.9096483023129448
Generation:  60%|██████    | 15/25 [1:27:37<1:20:33, 483.40s/it]WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155454f18e50> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

Generation:  16
Best f1_score score: 0.9105562055013967
Generation:  64%|██████▍   | 16/25 [1:28:03<51:52, 345.86s/it]  WARNING THIS INDIVIDUAL CAUSED AND EXCEPTION 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1553dc8a6200> 
 Negative values in data passed to MultinomialNB (input X) 
 Traceback (most recent call last):
  File "/common/ketrong/tpotexp/tpot2/tpot2/utils/eval_utils.py", line 53, in objective_nan_wrapper
    value = func_timeout.func_timeout(timeout, objective_function, args=[individual], kwargs=objective_kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator.py", line 623, in objective_function
    return objective_function_generator(
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/estimator_utils.py", line 55, in objective_function_generator
    cv_obj_scores = cross_val_score_objective(sklearn.base.clone(pipeline),x,y,scorers=scorers, cv=cv , fold=step)
  File "/common/ketrong/tpotexp/tpot2/tpot2/tpot_estimator/cross_val_utils.py", line 28, in cross_val_score_objective
    this_fold_pipeline.fit(X_train,y_train)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 759, in fit
    self._count(X, Y)
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/naive_bayes.py", line 881, in _count
    check_non_negative(X, "MultinomialNB (input X)")
  File "/common/ketrong/tpotexp/env/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1689, in check_non_negative
    raise ValueError("Negative values in data passed to %s" % whom)
ValueError: Negative values in data passed to MultinomialNB (input X)

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x155452937ac0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554741f4160> 

Generation:  17
Best f1_score score: 0.9105562055013967
Generation:  68%|██████▊   | 17/25 [1:38:10<56:34, 424.36s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545720d2d0> 

Generation:  18
Best f1_score score: 0.9105562055013967
Generation:  72%|███████▏  | 18/25 [1:48:18<55:57, 479.61s/it]Generation:  19
Best f1_score score: 0.9105562055013967
Generation:  76%|███████▌  | 19/25 [1:48:44<34:20, 343.38s/it]Generation:  20
Best f1_score score: 0.9119650512672497
Generation:  80%|████████  | 20/25 [1:49:46<21:33, 258.62s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x15545494d300> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554547e9ff0> 

Generation:  21
Best f1_score score: 0.9119650512672497
Generation:  84%|████████▍ | 21/25 [1:59:53<24:13, 363.27s/it]Generation:  22
Best f1_score score: 0.9119650512672497
Generation:  88%|████████▊ | 22/25 [2:00:10<12:58, 259.35s/it]Generation:  23
Best f1_score score: 0.9119650512672497
Generation:  92%|█████████▏| 23/25 [2:02:36<07:30, 225.26s/it]WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554527f45b0> 

WARNING AN INDIVIDUAL TIMED OUT: 
 <tpot2.search_spaces.pipelines.sequential.SequentialPipelineIndividual object at 0x1554741a1cc0> 

Generation:  24
Best f1_score score: 0.9119650512672497
Generation:  96%|█████████▌| 24/25 [2:12:43<05:39, 339.87s/it]Generation:  25
Best f1_score score: 0.9119650512672497
Generation: 100%|██████████| 25/25 [2:13:10<00:00, 246.02s/it]Generation: 100%|██████████| 25/25 [2:13:10<00:00, 319.61s/it]
2024-11-24 09:50:56,599 - distributed.scheduler - ERROR - Removing worker 'tcp://127.0.0.1:42121' caused the cluster to lose scattered data, which can't be recovered: {'DataFrame-7212280268743b8e0b2c7807150ee08e', 'ndarray-f70cb5088a4b38b195da3685bce072b9'} (stimulus_id='handle-worker-cleanup-1732470656.5996525')
Fitted
Pipeline(steps=[('iterativeimputer',
                 IterativeImputer(estimator=Ridge(), imputation_order='arabic',
                                  initial_strategy='median',
                                  n_nearest_features=69)),
                ('lgbmclassifier',
                 LGBMClassifier(max_depth=9, n_estimators=93, n_jobs=1,
                                num_leaves=129, verbose=-1))])
transform worked
try transform
transform worked
score start
train score: {'auroc': 1.0, 'accuracy': 1.0, 'balanced_accuracy': 1.0, 'logloss': 0.01514413268581291, 'f1': 1.0}
test score: {'auroc': 0.919855679125488, 'accuracy': 0.951, 'balanced_accuracy': 0.8440252974347542, 'logloss': 0.17470345797547632, 'f1': 0.886039886039886}
original test score: {'auroc': 0.9247186651144743, 'accuracy': 0.953, 'balanced_accuracy': 0.8511174960163146, 'logloss': 0.16857276488115974, 'f1': 0.8914527091787128}
score end
40701
lvl
0.01
type
MCAR
num_run
3
class_full
finished
all finished
full run takes
8.189883809619479
hours
DONE
